export const SET_MENU_STAT = 'SET_MENU_STAT';
export const SET_ROUTER_URL = 'SET_ROUTER_URL';
export const SET_ROUTER_CHANGE = 'SET_ROUTER_CHANGE';
export const SET_HEAD_ICON_COLOR = 'SET_HEAD_ICON_COLOR';
export const SET_HEAD_STYLE = 'SET_HEAD_STYLE';
export const SET_MENU_STYLE = 'SET_MENU_STYLE';
export const SET_MAIN_STYLE = 'SET_MAIN_STYLE';
export const SET_BUTTON_STYLE = 'SET_BUTTON_STYLE';
